echo "<html>
<head>
<title>Status of the jobs during the day</title>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
}
</style>
</head>
<body>
<p><font face='verdana' size='2' color='black'>Hello All,</font></p>
<p><font face='verdana' size='2' color='black'>Please find the below replication status </font></p>
<br>
<table style='width:40%'>
<tr bgcolor='LightGrey'>
    <th>Program#</th>
    <th>Status</th>
    <th>Group</th>
    <th>Lag at Chkpt</th>
        <th>Time Since Chkpt</th>
  </tr> "

file="/tmp/gghtml.lag"
 while IFS= read line
 do
 var1=$(echo "$line" | awk '{print $1}')
 var2=$(echo "$line" | awk '{print $2}')
 var3=$(echo "$line" | awk '{print $3}')
 var4=$(echo "$line" | awk '{print $4}')
 var5=$(echo "$line" | awk '{print $5}')
 echo "<tr>"
# echo "<td> $var1 </td>"
# echo "<td> $var2 </td>"
#echo $var3
echo "<td><font face='verdana' size='1' color='black'> $var1 </font></td>"
echo "<td><font face='verdana' size='1' color='black'> $var2 </font></td>"
if [ "$var3" == "ABENDED" -o "$var3" == "STOPPED" ]; then
        echo "<td><font face='verdana' size='1' color='red'> $var3 </font></td>"
else
        echo "<td><font face='verdana' size='1' color='green'> $var3 </font></td>"
fi
echo "<td><font face='verdana' size='1' color='black'> $var4 </font></td>"
echo "<td><font face='verdana' size='1' color='black'> $var5 </font></td>"
 echo "</tr>"
done <"$file"

echo "
 </table>
<p><font face='verdana' size='2' color='black'>Thank you !</font><br><font face='verdana' size='2' color='black'>DBA Team.</font><br>
<font face='verdana' size='1' color='red'>**This is autogenerated email via DB process.</font></p>
</body></html>
"
